### ISSUE TITLE
Should create in named folder, not current folder

### ISSUE THREAD

**Issue by msfeldstein** [vadimdemedes/create-ink-app#1]
create-react-app (and most other generators) will require a folder to generate into so you don't accidentally fill your root directory with a bunch of files.  Should be `npx create-ink-app my-app` to create the app at the directory `my-app`

**Comment by lslv1243** [comment]
Agreed. By accident I poluted my desktop, believing it would work like create-react-app.

**Comment by riongull** [comment]
Agreed, and if the developer wants to scaffold the app in the current working directory (after `mkdir my app && cd my-app` for example) they still can by calling `npx create-ink-app .` (the `.` referring to `my-app` in this case).

**Comment by LitoMore** [comment]
@vadimdemedes How do you think? I can make a PR if you need some help.

**Comment by vadimdemedes** [comment]
Agree, I like @riongull's solution with a dot to avoid creating a new folder.

@LitoMore Sure, go ahead!

**Comment by LitoMore** [comment]
@vadimdemedes OK. I have an active PR for you https://github.com/vadimdemedes/create-ink-app/pull/5 .

For less conflict in PR, we can solve this first.

**Comment by LitoMore** [comment]
@vadimdemedes OK. I have an active PR for you https://github.com/vadimdemedes/create-ink-app/pull/5 .

For less conflict in PR, we can solve #5 first.
