### ISSUE TITLE
`npx create-ink-app js-app` fails due to missing `.gitignore` in `/templates/_common/`

### ISSUE THREAD

**Issue by anddoutoi** [vadimdemedes/create-ink-app#30]
### Issue

It seems like the `.gitignore` file is missing in the package.

Makes the installer throw an exception and exit not copying any files to destination.

![image](https://user-images.githubusercontent.com/204784/229772144-b7d69843-3bc1-42da-b7f5-2194ed11b42e.png)

### Possible solution

https://stackoverflow.com/a/71232660 (not tested)

**Comment by Zadag** [comment]
Im getting this error as well. @anddoutoi Did you come up with a solution?

**Comment by Zadag** [comment]
@cthulhu-bot That makes sense!  I wound up installing globally and the copying the changes made to index in #31
