### ISSUE TITLE
create-ink-component

### ISSUE THREAD

**Issue by LitoMore** [vadimdemedes/create-ink-app#8]
Context: https://github.com/vadimdemedes/create-ink-app/pull/5#issuecomment-703118446

The logic of `create-ink-app` and `create-ink-component` are similar. I think we can add the command `create-ink-component` to this project.

For example:

```json
{
  "bin": {
    "create-ink-app": "cli.js",
    "create-ink-component": "cli.js"
  }
}
```

We can get the command name from `process.argv`.

@vadimdemedes What do you think?

**Comment by vadimdemedes** [comment]
I'd rather not mix the two and keep them standalone.
