### ISSUE TITLE
Getting a lot of strange errors on new Typescript project

### ISSUE THREAD

**Issue by KyleAMathews** [vadimdemedes/create-ink-app#9]
Not a typescripter much so confused :-D

<img width="647" alt="Screen Shot 2020-11-02 at 4 33 49 PM" src="https://user-images.githubusercontent.com/71047/97934003-3f6e7400-1d29-11eb-957c-bfc8b6f517ed.png">

**Comment by aManNamedJed** [comment]
I wanted to bump this -- I am sure it is something I am overlooking, but my Node won't execute the JSX files (the TS compiles fine for me), saying that I need to use the experimental modules flag, though I am on the newest Node release.
